name: deeplearning
channels:
- conda-forge
- defaults
dependencies:
- keras=2.1.5
- graphviz=2.38.0
- jupyter=1.0.0
- jupyterlab=0.3
- matplotlib=2.2.0
- numpy=1.14.2
- pillow=5.0.0
- pip=9.0.1=py36_5
- python=3.6.4
- pydot=1.2.4
- scipy=1.0.0
