version: 2
jobs:
  build:
    steps:
      # build and push Docker image
      - run: |
          docker build -t wit543/deeplearning:circleci .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push wit543/deeplearning:circleci
